### PR TITLE
Switch pysnmplib to version 5.0.21

### PR DESCRIPTION
**Pull request by IggePop**
Don't call await twice

### CODE REVIEW

**Comment by bieniu** [comment]
This change will cause an exception
```
Traceback (most recent call last):
  File "/home/maciek/develop/brother/example.py", line 52, in <module>
    loop.run_until_complete(main())
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/maciek/develop/brother/example.py", line 33, in main
    brother = await Brother.create(
              ^^^^^^^^^^^^^^^^^^^^^
  File "/home/maciek/develop/brother/brother/__init__.py", line 96, in create
    await instance.initialize()
  File "/home/maciek/develop/brother/brother/__init__.py", line 122, in initialize
    _, errstatus, errindex, _ = get_result
    ^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: await wasn't used with future
```
pysnmplib==5.0.20
python 3.11.2

**Comment by bieniu** [comment]
This change requires bump `pysnmplib` to version 5.0.21. They introduced a breaking change without announcement, again.

**Comment by IggePop** [comment]
Ok, that explains why the fix works for me. pysnmplib 5.0.21 is running on my site.

**Comment by bieniu** [comment]
Please update requirements.txt file.

**Review by bieniu — APPROVED** [review]
Looks good, thanks @IggePop

**Pull request merged**
